### ISSUE TITLE
Enhancement: Revamp README for Improved User Guidance

### ISSUE THREAD

**Issue by rahat2134** [Spandan-Bhattacharya/Solve_it#1]
This enhancement focuses on revitalizing the README to provide users with clearer and more comprehensive guidance. The current README, while functional, may benefit from a strategic update to enhance the user onboarding experience, streamline information, and ensure a smoother understanding of the project.

**Key Objectives:**

1. **Clarity in Setup Instructions:**
   Improve and clarify the setup instructions to ensure users, including newcomers, can easily set up and run the project without encountering any hurdles.

2. **Comprehensive Overview:**
   Expand on the project overview to provide a more detailed and informative introduction. This includes highlighting key features, use cases, and any prerequisites that users should be aware of.

3. **Usage Examples:**
   Incorporate clear and concise usage examples to assist users in quickly understanding how to interact with the project and utilize its functionalities.

4. **Updated Code Samples:**
   Ensure that any code samples in the README are up-to-date, accurate, and reflective of the current state of the project. This guarantees users have reliable references for implementation.

5. **Contributing Guidelines:**
   Enhance the contributing guidelines to encourage community involvement. Clear instructions on how users can contribute, report issues, and suggest improvements will be emphasized.

**Benefits:**

- **Improved User Onboarding:**
  Users, especially those new to the project, will experience a more streamlined onboarding process with clearer instructions and examples.

- **Reduced Ambiguity:**
  By enhancing clarity in the README, potential sources of confusion or ambiguity will be minimized, resulting in a more user-friendly experience.

- **Facilitated Contributions:**
  The updated contributing guidelines will encourage community engagement, making it easier for users to contribute to the project and share feedback.

This README enhancement aims to optimize the user experience, making the project more accessible and user-friendly for both new and existing contributors.

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya assign this to me (JWOC).

**Comment by Spandan-Bhattacharya** [comment]
I have to close this issue, for mentees cannot make issues yet.
Make the issue once the coding period starts and you will be assigned it.

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya, I asked the organizer of JWOC about mentees creating issues. They said that mentees can create issues, but these issues will only be assigned to them during the coding period.

**Comment by rahat2134** [comment]
if you want i can send screenshot -
<img width="601" alt="Screenshot 2024-01-12 at 12 20 06 AM" src="https://github.com/Spandan-Bhattacharya/Solve_it/assets/136263179/6338f863-a2bb-4526-adf3-e3077616e486">

**Comment by rahat2134** [comment]
hope this helps and if you agree i can create some issues.As i go through your repo.

**Comment by rahat2134** [comment]
Please reply as soon as possible

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya  which means i cant raise issue now . I can only raise issue when coding phase start? or i can raise the issue now but you will assign me this when coding phase start?

**Comment by Spandan-Bhattacharya** [comment]
Yes you can't create issues right now.
You can do so after the coding phase begins.

**Comment by rahat2134** [comment]
ok thx
