### ISSUE TITLE
Improve the Footer.

### ISSUE THREAD

**Issue by SohanRC** [Spandan-Bhattacharya/Solve_it#100]
@Spandan-Bhattacharya  Want to improve the footer design to make it look more professional. I am attaching the screenshot here. Please assign me under JWOC 2024.

Like this : 
![12-Responsive Footer Templates](https://github.com/Spandan-Bhattacharya/Solve_it/assets/124901633/f5296933-ebe2-4955-8ff0-e4de080aadcc)

**Comment by Spandan-Bhattacharya** [comment]
The design does not fit the theme of the website I think

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by SohanRC** [comment]
> The design does not fit the theme of the website I think

I think with a slight modification it will look good.

**Comment by Spandan-Bhattacharya** [comment]
Okay I will give you the footer colour theme, follow it.
for the background:
linear-gradient(rgb(10, 18, 31) 2.5%, rgb(10, 22, 41) 43%, rgb(10, 18, 31) 100%)
for the text:
#ffb780
