### ISSUE TITLE
Add footer to the about page.

### ISSUE THREAD

**Issue by Sneha123-zudo** [Spandan-Bhattacharya/Solve_it#101]
I want to add footer to the about page for the enhancement of the page as it contains the navbar but not footer . Please assign me this issue.

**Comment by Spandan-Bhattacharya** [comment]
![Uploading image.png…]()
Go for it!! @Sneha123-zudo 
Do the footer as per this design.

**Comment by vermaanurag1532** [comment]
please Assign it to me
