### ISSUE TITLE
UI: Go-To-Top Icon not visible

### ISSUE THREAD

**Issue by AryanPahuja21** [Spandan-Bhattacharya/Solve_it#104]
The  Go-To-Top icon is not visible when not in the active state. I would like to fix it.

![Screenshot 2024-01-23 175027](https://github.com/Spandan-Bhattacharya/Solve_it/assets/139960070/99eb7501-d56f-49c3-9450-2550ced01298)

@Spandan-Bhattacharya please assign this issue to me under JWOC'24.

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by Spandan-Bhattacharya** [comment]
@AryanPahuja21 Go for it!
