### ISSUE TITLE
Fix: `Suggestions not working` in Search bar

### ISSUE THREAD

**Issue by this-is-yaash** [Spandan-Bhattacharya/Solve_it#106]
## Suggestions not displaying
Upon entering the search keyword, it does **not display the suggestions** under the search bar (or) even when clicking on the search button itself.
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/84762257/41d4a530-259b-461a-a577-433e017e1a7d)

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @this-is-yaash

**Comment by this-is-yaash** [comment]
## Bug
[Screencast from 2024-01-24 21-54-26.webm](https://github.com/Spandan-Bhattacharya/Solve_it/assets/84762257/d39ea4aa-8996-408c-91d0-8e98dd84d2bc)

- Current `CSS` properties were collapsing with `result-box` & `search-box`
- It works when I press <kbd>TAB</kbd> 
- But displaying the cropped `result-box` inside the nav-bar & also glitching the whole nav for this **Bug**.

**Comment by this-is-yaash** [comment]
Can you change the difficulty tag for this issue?
Because this will definitely take some time to fix.

Thanks!

**Comment by Spandan-Bhattacharya** [comment]
Okay I will change the tag upon seeing the solution.

**Comment by this-is-yaash** [comment]
@Spandan-Bhattacharya Submitted PR #121
Please review it & let me know.

**Thanks!**
