### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by Sruti-sahini** [Spandan-Bhattacharya/Solve_it#12]
Hello @Spandan-Bhattacharya 
I want to improve the UI of the page.
Please assign me this under JWoC'24.

**Comment by Spandan-Bhattacharya** [comment]
You have been assigned another issue, after its done, I can assign you this one. This specific issue won't be assigned to others.

**Comment by Spandan-Bhattacharya** [comment]
Everyone if you have not joined the Discord server yet, please do so, as I will be sharing instructions on the solve-it! channel under projects.
Link to the server:
https://discord.gg/bcgZ9RZZ8r

**Comment by Sruti-sahini** [comment]
@Spandan-Bhattacharya  Is this issue closed ?

**Comment by Spandan-Bhattacharya** [comment]
Yeah I had to close this issue as the UI of the pages are assigned as per issue #9, #8, #19

**Comment by Sruti-sahini** [comment]
okay!
