### ISSUE TITLE
addition of 16 * 16 sudoku

### ISSUE THREAD

**Issue by tushargupta1504** [Spandan-Bhattacharya/Solve_it#120]
addition of 16 *16 5*5 and every which is poss. 
also to improve the text design 
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/138330699/9c82c9ca-1f1b-455e-a8de-85868e1d717e)
in this image 
just below hre

**Comment by Spandan-Bhattacharya** [comment]
Add the 16x16 solver for now. @tushargupta1504

**Comment by Spandan-Bhattacharya** [comment]
Any updates?

**Comment by tushargupta1504** [comment]
Yeah completing on the way...

**Comment by Spandan-Bhattacharya** [comment]
Okay

**Comment by Spandan-Bhattacharya** [comment]
Any updates? Make sure its implemented by tomorrow. @tushargupta1504

**Comment by SohanRC** [comment]
@Spandan-Bhattacharya Please assign me under JWOC 2024 if not completed !

**Comment by Spandan-Bhattacharya** [comment]
@tushargupta1504 I am unassigning you.

**Comment by Spandan-Bhattacharya** [comment]
@SohanRC Go for it!

**Comment by Spandan-Bhattacharya** [comment]
@SohanRC updates?

**Comment by SohanRC** [comment]
> @SohanRC updates?

I am working on it ! Please give some time !
