### ISSUE TITLE
Add : Crossword Game

### ISSUE THREAD

**Issue by Surajit0573** [Spandan-Bhattacharya/Solve_it#128]
I am planning to develop a simple crossword game using HTML, CSS, and JavaScript. The game will consist of multiple sets of questions (word hints) and answers (words), stored in a JavaScript object file. Upon starting the game, a random set will be selected, and the game will begin. Players can play the game and check their answers for correctness.

Please assign me under JWOC 2024, if approved.

**Comment by Spandan-Bhattacharya** [comment]
The website currently does not have any games, it only has the solvers. I am planning on implementing it at a later date.
