### ISSUE TITLE
[Feature]: Enhance Contributor Onboarding -Add Local Installation Video to README

### ISSUE THREAD

**Issue by rahat2134** [Spandan-Bhattacharya/Solve_it#129]
Description
Contributor onboarding could be improved by providing a visual guide on how to install the project locally. Adding a video demonstration will help newcomers understand the setup process more effectively.

Expected Outcome:
The addition of a video tutorial in the README, demonstrating the step-by-step process of installing the project locally, will make it easier for contributors, especially those new to the codebase.

Proposed Content:
A short video covering the following:

Cloning the repository.
Installing dependencies.
Configuring any necessary settings.
Running the project locally.
Problem
Contributor onboarding could be improved by providing a visual guide on how to install the project locally. Adding a video demonstration will help newcomers understand the setup process more effectively.

Proposed Solution
Record a concise video for that.

-> raising under #JWOC

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya assign this issue to me under JWOC. Want to make a professional video for local installation for good readme.md

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @rahat2134

**Comment by Spandan-Bhattacharya** [comment]
Any updates?

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya hmm will commit by EOD.

**Comment by Spandan-Bhattacharya** [comment]
Okay

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya please change the difficulty level as per PR.
