### ISSUE TITLE
[FIX]: Nav bar and Overall styling

### ISSUE THREAD

**Issue by Ashutosh104** [Spandan-Bhattacharya/Solve_it#13]
The nav bar should be more stylish and the whole page should be much attractive.

**Comment by Spandan-Bhattacharya** [comment]
@Ashutosh104  you are assigned this issue. Good Luck!!

**Comment by Spandan-Bhattacharya** [comment]
@Ashutosh104 work on only the Nav bar.

**Comment by Spandan-Bhattacharya** [comment]
Everyone if you have not joined the Discord server yet, please do so, as I will be sharing instructions on the solve-it! channel under projects.
Link to the server:
https://discord.gg/bcgZ9RZZ8r
