### ISSUE TITLE
Change in text colour 

### ISSUE THREAD

**Issue by TanushreeBorase** [Spandan-Bhattacharya/Solve_it#131]
<img width="814" alt="image" src="https://github.com/Spandan-Bhattacharya/Solve_it/assets/130696335/bd2c28f2-613e-4474-b469-92964c21d116">

I would like to change colour of txt from black to white for visibility below Find Solutions to all those mind-numbing puzzles right here!.

**Comment by Spandan-Bhattacharya** [comment]
This is too small of an issue for me to be able to give it a dedicated issue.
You can find some other minor issues and club them together to raise an issue. @TanushreeBorase
