### ISSUE TITLE
Different color to the user input cells of sudoku solvers

### ISSUE THREAD

**Issue by bera474** [Spandan-Bhattacharya/Solve_it#132]
I want to color differently to the user input cells and other cells of the sudoku solvers . It will improve the User Interface of the website as well as user will understand the solution easily . Please assign me this issue under JWOC 2024.

https://github.com/Spandan-Bhattacharya/Solve_it/assets/118124036/95a291f5-426e-4976-b63b-9fee668601f6

![Screenshot (76)](https://github.com/Spandan-Bhattacharya/Solve_it/assets/118124036/d4273154-07b7-46bc-a005-827dd603715c)

![Screenshot (77)](https://github.com/Spandan-Bhattacharya/Solve_it/assets/118124036/6e7550f2-a927-445e-b4ee-39e64966ed37)

![Screenshot (78)](https://github.com/Spandan-Bhattacharya/Solve_it/assets/118124036/757ea5b2-a829-475b-80fa-f0ff3fb160a4)

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @bera474 But can you change the colour of the number instead the cell?

**Comment by bera474** [comment]
@Spandan-Bhattacharya Yes I can , which colour do you suggest ?

**Comment by Spandan-Bhattacharya** [comment]
Like black for the given input, and blue for the digits decoded by the solver.
