### ISSUE TITLE
UI: Enhance Search Box in the Navbar

### ISSUE THREAD

**Issue by antilneeraj** [Spandan-Bhattacharya/Solve_it#133]
The current Navbar Search Box requires improvements for a more enhanced look to match the theme. This enhancement aims to address visual appeal, responsiveness across devices, and modular implementation of the box

@Spandan-Bhattacharya Please assign this issue to me under JWOC.

**Comment by Spandan-Bhattacharya** [comment]
Can you show any design you have in mind?

**Comment by antilneeraj** [comment]
@Spandan-Bhattacharya Somewhat similar to this one below:

![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/98269887/bb5ae188-8923-48a0-8fee-c762a14b69ce)

**Comment by antilneeraj** [comment]
when clicked on the search icon on the left, the search box will open up aside and the search icon will change into a cross icon, when clicked will make it initial (the search icon only).

The process will be transitioned.

**Comment by Spandan-Bhattacharya** [comment]
Okay Go for it!
Make sure it works with the hamburger style menu too.
As that has been implemented to make it responsive.
