### ISSUE TITLE
UI : Navbar of "About" page is not consistent with other pages

### ISSUE THREAD

**Issue by Surajit0573** [Spandan-Bhattacharya/Solve_it#134]
About page: 
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/ecd7d6e5-a4b3-48b8-9de5-b59ba69c40a2)

Other page : 
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/eb65c9ef-b77f-4a2f-a2d8-4d995800fea0)

Navbar of about page is not consistent with other pages ....I want fix this.

Please assign me under JWOC 2024, if approved.

**Comment by Spandan-Bhattacharya** [comment]
This is being worked on by another mentee currently.
