### ISSUE TITLE
New solver addition.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#142]
The game:
The user will be given 4 numbers, and a target value.
The user has to use all 4 values, and using some combination of +,-,×,÷(these can be repeated, the numbers cannot be repeated) to get to the target value.
Only BODMAS rule will be followed, no brackets allowed.
Eg:
Numbers given: 2, 3, 1 9, target: 14
One possible solution: 2*3 -1+9=14
Eg: Numbers given 2, 2 ,4,1, target =0
One possible solution: 2-2+4*0= 2-2+ 0=2-2=0
Implement a solver, NOT the game.

The use will give the input 4 numbers and the target, if its possible to achieve, give the solution, else notify the user that it is not possible.

**Comment by Surajit0573** [comment]
please assign this to me under JWOC 2024

**Comment by Spandan-Bhattacharya** [comment]
@Surajit0573 go for it!

**Comment by Spandan-Bhattacharya** [comment]
Any updates?

**Comment by Surajit0573** [comment]
working on it....

**Comment by Spandan-Bhattacharya** [comment]
Okay
