### ISSUE TITLE
Math puzzle game

### ISSUE THREAD

**Issue by Aashi19234** [Spandan-Bhattacharya/Solve_it#144]
I would like to add a new game called math puzzle game in which  a puzzle will be generated with a mathematical expression and missing numbers or operators. and  users  will be allowed to fill in the missing parts to make the equation correct. User will be provided a particular number of attempts before the solution is shown, and then user can proceed to the next puzzle.
If u find this idea interesting, then please assign me this issue under JWOC'24.

**Comment by Spandan-Bhattacharya** [comment]
Currently the website has only solvers.
These can be implemented in Phase 2.

**Comment by Aashi19234** [comment]
@Spandan-Bhattacharya Okay, please assign it me once the phase-2 starts, Thank you.
