### ISSUE TITLE
Feature: Adding a FAQ Page for the website.

### ISSUE THREAD

**Issue by antilneeraj** [Spandan-Bhattacharya/Solve_it#146]
## Description
I want to create a FAQ page that answers a variety of questions regarding the project.

## Reference of Template

![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/98269887/12b54893-f02d-4899-a070-913d71cc3326)
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/98269887/07468c10-2fa7-4913-ac97-029b8a7df992)

## Checklist

- [x] I'll Follow the Contributing Guidelines
- [x] The FAQ Page will be Responsive
- [x] The Design will be According to the theme of the Website

**Comment by antilneeraj** [comment]
@Spandan-Bhattacharya Can you please assign this issue to me under JWOC.

**Comment by Spandan-Bhattacharya** [comment]
Go for it!
