### ISSUE TITLE
Removal of up-down arrow on the boxes

### ISSUE THREAD

**Issue by Anushka-Bhowmick** [Spandan-Bhattacharya/Solve_it#148]
- I want to remove the up-down arrow on the grid inputs so that the user can type the number directly
- Also, I would like to show the numbers in a different color if the user doesn't type a number in a specified range

**Comment by Spandan-Bhattacharya** [comment]
@Anushka-Bhowmick Go for it!

**Comment by Spandan-Bhattacharya** [comment]
@Anushka-Bhowmick Go for it!
