### ISSUE TITLE
nav bar links fixing 

### ISSUE THREAD

**Issue by thesri** [Spandan-Bhattacharya/Solve_it#15]
The links for contact and about from the nav bar arnt working. we can add the related information there , please kindly assign this issue to me under JWOC 2024

**Comment by Spandan-Bhattacharya** [comment]
This issue has already been raised in issue no. #13 . If the assigned mentee does not fix the issue, it will be reassigned to others.

**Comment by Spandan-Bhattacharya** [comment]
Everyone if you have not joined the Discord server yet, please do so, as I will be sharing instructions on the solve-it! channel under projects.
Link to the server:
https://discord.gg/bcgZ9RZZ8r

**Comment by pranjal12-web** [comment]
@Spandan-Bhattacharya Kindly assign this issue to me under JWoC'24

**Comment by Spandan-Bhattacharya** [comment]
@thesri I am assigning the creation of the about and Contact pages to you.  In the about page, write about the project, and in the contact details, i will provide you the details.

**Comment by thesri** [comment]
okay please provide me the details @Spandan-Bhattacharya
