### ISSUE TITLE
UI : quick links are appearing without space

### ISSUE THREAD

**Issue by Anushkabh** [Spandan-Bhattacharya/Solve_it#155]
![Screenshot (106)](https://github.com/Spandan-Bhattacharya/Solve_it/assets/99523033/baad4253-3e53-489f-b3f2-0cd5122cd2cc)
 i want to add bullets type design in between so that it can be distinguished as different

**Comment by Anushkabh** [comment]
@Spandan-Bhattacharya kindly assign this under jwoc

**Comment by Spandan-Bhattacharya** [comment]
I just myself fixed it right now😅.
I did it before the issue was raised😂
