### ISSUE TITLE
Minor Changes & Fixes - navbar&footer

### ISSUE THREAD

**Issue by this-is-yaash** [Spandan-Bhattacharya/Solve_it#156]
## Navigation Bar
Current nav-bar matches the site UI & looks very good comparing to the previous design.

But I want to propose some changes to make it look better,
- Adding Icons beside the texts in nav-bar.
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/84762257/989a1843-b4d6-408f-a76c-81477a878824)
- Increasing the *height* of the navbar. Which will make the nav-bar **evenly aligned & spaced**.(Like the below example)
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/84762257/ba9b6d48-8295-4cbb-a9a9-e2b3d7d37734)

### Now:
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/84762257/07da904b-ed5b-43d9-a478-0be7f047d13b)
### After:
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/84762257/92751089-a75b-42a9-97ed-a88f0a074b93)
*Hovering on the text will look better rather than stuffing it inside with less space.*

## Footer

- Adding mailto function in email
- Adding map location to the college name
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/84762257/c0a78e47-aa7f-4ce8-8a55-4dc8d78804aa)

- If possible,can
  - changing actual phone number, *(or)
  - removing the *phone number* part

**Comment by Spandan-Bhattacharya** [comment]
Go for it!

**Comment by this-is-yaash** [comment]
What about the phone number?
should I remove it?

**Comment by Spandan-Bhattacharya** [comment]
Yes remove it

**Comment by Spandan-Bhattacharya** [comment]
any updates? @this-is-yaash

**Comment by this-is-yaash** [comment]
@Spandan-Bhattacharya 
I'll submit PR with 11pm

**Comment by this-is-yaash** [comment]
Additionally, please provide your email for inclusion in the contact form.

**Comment by Spandan-Bhattacharya** [comment]
spandanbhattacharya.sb@gmail.com

**Comment by this-is-yaash** [comment]
@Spandan-Bhattacharya 
Submitted PR, please review it.
Thanks!
