### ISSUE TITLE
Add Loading page to your website

### ISSUE THREAD

**Issue by Sneha123-zudo** [Spandan-Bhattacharya/Solve_it#157]
I want to add loading page to the website as when someone will open the website the loading page will come first then the main website content. It will improve the UI of the webpage also .

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @Sneha123-zudo

**Comment by prakharsingh-74** [comment]
I would like to coontribute on this issue if @Sneha123-zudo is not contributing on it

**Comment by prakharsingh-74** [comment]
@Spandan-Bhattacharya I would like to contribute under JWOC in this issue if @Sneha123-zudo is not working on this issue.

**Comment by Spandan-Bhattacharya** [comment]
@Sneha123-zudo any updates?

**Comment by Sneha123-zudo** [comment]
I am working on it .

**Comment by Spandan-Bhattacharya** [comment]
@Sneha123-zudo any updates?
