### ISSUE TITLE
Improving interface.

### ISSUE THREAD

**Issue by divyanshhii** [Spandan-Bhattacharya/Solve_it#16]
Hello @Spandan-Bhattacharya
I wish to make the interface  look better of 4x4 sudoku page and insert a back button which returns to the homepage.
Please assign me this under JWoC'24.

**Comment by Spandan-Bhattacharya** [comment]
This issue has already been assigned as per the issue #9 . If the issue in not closed in the given time, it will be re assigned.

**Comment by Spandan-Bhattacharya** [comment]
Everyone if you have not joined the Discord server yet, please do so, as I will be sharing instructions on the solve-it! channel under projects.
Link to the server:
https://discord.gg/bcgZ9RZZ8r
