### ISSUE TITLE
Make the NavBar for pages responsive with Hamburger.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#161]
The Home Page navbar is already responsive, just need to change the colour of the hamburger inset to match the current navbar theme.

Make the navbar for the other pages responsive as well, with a hamburger for mobile devices.

**Comment by SohanRC** [comment]
Please assign me under JWOC 2024.

**Comment by Anushkabh** [comment]
@Spandan-Bhattacharya assign me this issue under JWOC

**Comment by Spandan-Bhattacharya** [comment]
@Anushkabh Go for it!

**Comment by Spandan-Bhattacharya** [comment]
@Anushkabh Any updates?

**Comment by Anushkabh** [comment]
> @Anushkabh Any updates?

yes I am working on it .. hopefully by tomorrow i will push the changes

**Comment by Sneha123-zudo** [comment]
I'm intrested in this issue , please assign me under JWOC'24

**Comment by SohanRC** [comment]
> Please assign me under JWOC 2024.

Please assign me under JWOC 2024 if not completed !

**Comment by Spandan-Bhattacharya** [comment]
@Anushkabh Any updates?

**Comment by Anushkabh** [comment]
> @Anushkabh Any updates?

i actually fallen sick .. so couldn't push yesterday.. but i am hopeful of doing it today

**Comment by Spandan-Bhattacharya** [comment]
Okay take care. Try to push it by today @Anushkabh

**Comment by Sneha123-zudo** [comment]
Please assign me this issue under JWOC

**Comment by Spandan-Bhattacharya** [comment]
@Anushkabh I have to unassign you.

**Comment by Spandan-Bhattacharya** [comment]
@SohanRC Go for it

**Comment by Spandan-Bhattacharya** [comment]
@SohanRC any updates?

**Comment by SohanRC** [comment]
> @SohanRC any updates?

I am working on it ! Please give sometime
