### ISSUE TITLE
Add reset button to Number solver.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#165]
The Number Solver currently does not have any reset function.
Implement a button which when pressed, erases all the given user input and erases the solution box.
Also, alert the user if they have not filled all the fields.

**Comment by Surajit0573** [comment]
Assign this to me under JWOC 2024

**Comment by Spandan-Bhattacharya** [comment]
@Surajit0573 Go for it!

**Comment by prakharsingh-74** [comment]
@Spandan-Bhattacharya i would like to contribute in this issue if @Surajit0573 is not working on it.

**Comment by Surajit0573** [comment]
@prakharsingh-74 I am working on it.
