### ISSUE TITLE
BUG: Sudoku Solver

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#166]
See the video for the problem.
https://github.com/Spandan-Bhattacharya/Solve_it/assets/95448248/1651502d-3c85-4795-a134-f8fb0e41731a

The reset button does reset the colours of the numbers when it is pressed.
Correct it for all 3 solvers.

**Comment by avirupnandi1** [comment]
assign me this under JWOC

**Comment by Spandan-Bhattacharya** [comment]
@avirupnandi1 Go for it!

**Comment by Spandan-Bhattacharya** [comment]
Any updates?

**Comment by avirupnandi1** [comment]
Doing it by tonight
