### ISSUE TITLE
Enhance the validity checker in the Sudoku Solvers.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#167]
Currently the solver tells an input invalid if it itself does not follow the rules of sudoku i.e. some rows or column or box have the same element more than once.
The user input can have many solutions and the solver gives the 1st one it finds out.

Now, an actual valid Sudoku input must have only 1 solution. ONLY ONE.
So, change the validity function such that

-  it gives output only if the given input has only 1 solution.
- If it has more than 1 solution, it tells the user that it has more than 1 solution and thus the input is invalid, and after saying this, it outputs one of the valid answers.
- If the given input has no solution, it tells that to the user and resets the grid.
- Currently the message to the user is given in the form of a single line. Add a section to the page called validity or verdict, where the message to the user is made to pop out. In case the input is correct, output OK in the section.

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya  assign this issue to me under JWOC.

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @rahat2134

**Comment by Spandan-Bhattacharya** [comment]
@rahat2134 any updates?

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya taking time, still working on it.

**Comment by antilneeraj** [comment]
@Spandan-Bhattacharya Can you please assign this issue to me under JWOC if not completed by the assignee yet and also the assignee has passed the deadline to submit a PR.

**Comment by Spandan-Bhattacharya** [comment]
@rahat2134 any updates?

**Comment by rahat2134** [comment]
> @rahat2134 any updates?

I sent u discord dm.
