### ISSUE TITLE
Add back to home button in Number Solver.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#168]

**Comment by Anushkabh** [comment]
@Spandan-Bhattacharya kindly assign this under JWOC

**Comment by Spandan-Bhattacharya** [comment]
Go for it @Anushkabh

**Comment by jaymehta002** [comment]
assign me this issue for quick fix

**Comment by Anushkabh** [comment]
kindly merge @Spandan-Bhattacharya  if satisfied 
#170 
![Screenshot (107)](https://github.com/Spandan-Bhattacharya/Solve_it/assets/99523033/dfe2f0aa-cd50-4452-9ca7-fbe160071428)
