### ISSUE TITLE
New Solver addition: Word Unjumbler

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#169]
The user will provide some letters, and the solver will provide possible words that can be formed using the letters.
Eg:
user input :NAHD
Output:
4 letter: 
HAND
3 letter:
dah
had
nah
and
dan
2 letter:
ah
ha
ad
an
da
na

The output words can be found in a dictionary.

**Comment by prakharsingh-74** [comment]
I can solve this issue but need an api key that store these words in the backend and from them when the user entered the jumbled word js code will solve it and displayy on the frontend site

**Comment by Spandan-Bhattacharya** [comment]
Currently i am not planning on implementing backend thus if possible, store a small number of words in the frontend itself.
Yes this will make the solver not very powerful, but it will work for now.

**Comment by prakharsingh-74** [comment]
ok
