### ISSUE TITLE
Revamp README for Improved User Guidance 

### ISSUE THREAD

**Issue by rahat2134** [Spandan-Bhattacharya/Solve_it#17]
This enhancement focuses on revitalizing the README to provide users with clearer and more comprehensive guidance. The current README, while functional, may benefit from a strategic update to enhance the user onboarding experience, streamline information, and ensure a smoother understanding of the project.
Key Objectives:
1. Clarity in Setup Instructions: Improve and clarify the setup instructions to ensure users, including newcomers, can easily set up and run the project without encountering any hurdles.
2. Comprehensive Overview: Expand on the project overview to provide a more detailed and informative introduction. This includes highlighting key features, use cases, and any prerequisites that users should be aware of.
3. Usage Examples: Incorporate clear and concise usage examples to assist users in quickly understanding how to interact with the project and utilize its functionalities.
4. Updated Code Samples: Ensure that any code samples in the README are up-to-date, accurate, and reflective of the current state of the project. This guarantees users have reliable references for implementation.
5. Contributing Guidelines: Enhance the contributing guidelines to encourage community involvement. Clear instructions on how users can contribute, report issues, and suggest improvements will be emphasized.
Benefits:
* Improved User Onboarding: Users, especially those new to the project, will experience a more streamlined onboarding process with clearer instructions and examples.
* Reduced Ambiguity: By enhancing clarity in the README, potential sources of confusion or ambiguity will be minimized, resulting in a more user-friendly experience.
* Facilitated Contributions: The updated contributing guidelines will encourage community engagement, making it easier for users to contribute to the project and share feedback.
This README enhancement aims to optimize the user experience, making the project more accessible and user-friendly for both new and existing contributors.

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya  assign this issue to me after tomorrow evening. Thank You.

**Comment by Spandan-Bhattacharya** [comment]
@rahat2134 you are assigned this issue. Best of luck!!

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya Thank You So much

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya  pls check it and let me know if any updation u want?

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya please mention my name in spreadsheet 🙂
