### ISSUE TITLE
Add Icons to top-navbar in FAQ Page

### ISSUE THREAD

**Issue by this-is-yaash** [Spandan-Bhattacharya/Solve_it#172]
Issue:
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/84762257/e1145b28-8511-458c-be38-55f3eae43bb6)
Adding Icons to the Top-NavBar in the FAQ section

If this issue is valid, then assign me work on it under **JWOC**

**Comment by Spandan-Bhattacharya** [comment]
The navbar for the FAQ section will be changed, so no need to spend time on that currently.
You can insert the icons in the navbar of all the others pages.

**Comment by this-is-yaash** [comment]
Yeah, thanks!🙌
