### ISSUE TITLE
hover effect for the icons in the contributors page

### ISSUE THREAD

**Issue by thesri** [Spandan-Bhattacharya/Solve_it#173]
hover effect for the icons in the contributors page will make it look more good and cool , please assign this under jwoc 2024

**Comment by Spandan-Bhattacharya** [comment]
Which icons? the circle within which the contributor's profile picture is present?

**Comment by thesri** [comment]
> Which icons? the circle within which the contributor's profile picture is present?

Yes

**Comment by Spandan-Bhattacharya** [comment]
Okay go for it!
