### ISSUE TITLE
New Solver Addition : 8 Puzzle

### ISSUE THREAD

**Issue by Surajit0573** [Spandan-Bhattacharya/Solve_it#179]
I want to add a new solver for "8 Puzzle" Game.

Game : Given a 3×3 board with 8 tiles (every tile has one number from 1 to 8) and one empty space. The objective is to place the numbers on tiles to match the final configuration using the empty space. We can slide four adjacent (left, right, above, and below) tiles into the empty space. 

This solver will solve 8-puzzle game with various tree search techniques. It also visualizes the search tree.

Assign me under JWOC 2024, if approved.

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @Surajit0573
