### ISSUE TITLE
N-Queen Problem solver

### ISSUE THREAD

**Issue by Aashi19234** [Spandan-Bhattacharya/Solve_it#182]
This game is a classic chess puzzle where the challenge is to place N queens on an N×N chessboard in such a way that no two queens threaten each other. This means that no two queens can be in the same row, column, or diagonal. I would add a solution for the N-Queens Problem which  aims to find a valid placement for N queens.
Please assign it to me under JWOC'24.

**Comment by Spandan-Bhattacharya** [comment]
@Aashi19234  Go for it! Show the output in the form of a chess board on which the queens are placed.
