### ISSUE TITLE
Enhance UI of the number solver and make it responsive

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#183]
Make the Number solver responsive and change the UI to match the theme of the website.

- Make the website responsive
- When negative numbers are used, place them within brackets in the output field.
- use the divide sign instead of the '/' in the output field.
- Make the UI more cohesive with the other solvers.

**Comment by antilneeraj** [comment]
@Spandan-Bhattacharya I've submitted a pull request for my assigned issue, incorporating necessary changes and optimizations. I hope you find the updates satisfactory. Post-merge, I kindly request you to assign this issue to me under `JWOC`.

**Comment by Spandan-Bhattacharya** [comment]
@antilneeraj Go for it!
