### ISSUE TITLE
Footer Design and codebase update

### ISSUE THREAD

**Issue by aindree-2005** [Spandan-Bhattacharya/Solve_it#19]
Adding Links and proper design to footer
Revamping Web Page Design with puzzle-themed design
Fixing an overall global css style for website.
@Spandan-Bhattacharya can I work on this under JWOC?

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @aindree-2005

**Comment by Spandan-Bhattacharya** [comment]
@aindree-2005 Any updates?

**Comment by Spandan-Bhattacharya** [comment]
I am reassigning the issue.

**Comment by Spandan-Bhattacharya** [comment]
Work on the footer of the page, keeping it in line with the theme of the page.

**Comment by debuuuu007** [comment]
I would like to work on this under jwoc24

**Comment by Spandan-Bhattacharya** [comment]
@debuuuu007 Go for it!

**Comment by debuuuu007** [comment]
I think you have forgot to assign me, can you please assign me with the issue.

**Comment by Spandan-Bhattacharya** [comment]
Yeah, my mistake, sorry!
