### ISSUE TITLE
Enhance the UI of the Tower of Hanoi solver.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#191]
The Solver has a great animation, no need to change that.
Implement the following features:

- Add a back to home button
- Remove the New Game button: Implement it's functionality using only the 'number of discs' selector( When the user selects a number from the drop down, the user selected number of discs are reset to the left most column)
- The field where the steps are shown, make it so that it does not have scrollbar, i.e. if the number of steps is large, the field increases in length.
-  Make the UI of the page match the UI of the overall website in terms of fonts, colours and designs.

**Comment by vishal2005025** [comment]
please assign it to me under JWOC'2024.

**Comment by Sneha123-zudo** [comment]
Please assign me this issue under JWOC'24 , I'm intrested in this issue

**Comment by Spandan-Bhattacharya** [comment]
@vishal2005025 Go for it!

**Comment by vishal2005025** [comment]
ok!

**Comment by Spandan-Bhattacharya** [comment]
@vishal2005025 any updates?

**Comment by vishal2005025** [comment]
Sir , I will create pr till today.
