### ISSUE TITLE
Redundant feature removal 

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#196]
In the 4x4 sudoku, the "solve" button is no longer needed as it's function is being done by the solve solution button.
Remove the solve button, and position the rest of the elements accordingly.

**Comment by kaif969** [comment]
please assign it to me under JWOC'2024.

**Comment by Spandan-Bhattacharya** [comment]
@kaif969 Go for it!

**Comment by Spandan-Bhattacharya** [comment]
@kaif969 any updates?

**Comment by kaif969** [comment]
> @kaif969 any updates?

I will work on it.

**Comment by Spandan-Bhattacharya** [comment]
This issue is open for assignment.
