### ISSUE TITLE
Word Unjumbler bug

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#197]
Currently if the character set of word in the dictionary is a subset of the character of the input word, it calls that word a unjumbled word found from the input.
That is not always true.

Eg: Ahead : character set=a,h,e,d
dada : character set = a,d
Thus "dada" character set is a subset of "ahead" character set.
Thus it is giving it as a solution, which is incorrect.
Fix this bug.

**Comment by yashasvini121** [comment]
Hey @Spandan-Bhattacharya, please assign me this issue under JWOC.

**Comment by Spandan-Bhattacharya** [comment]
@yashasvini121 Go for it!

**Comment by Spandan-Bhattacharya** [comment]
@yashasvini121 any updates?
