### ISSUE TITLE
Make the Search bar functional.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#198]
Currently, the search bar does not have any functionality.
Make it such that it works like the search bar in the JWOC Website.
No need to implement it for tags, just searching by the solver name will be implemented.
https://www.jwoc.tech/projects

**Comment by prakharsingh-74** [comment]
@Spandan-Bhattacharya  i would like to work on this issue please assigned it to me under JWOC'24

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @prakharsingh-74

**Comment by SuvayuN** [comment]
I want to work on this issue under JWOC'24
