### ISSUE TITLE
Make the bubbles in the home screen background more uniformly placed.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#199]
Currently, the bubbles in the background are present more in the left side that the right, spread it uniformly, also, make a few of the bubbles golden in colour.
I will increase the difficulty to hard, if you can randomly generate the positions of the bubbles, with values giving the page a uniform feel.

**Comment by Sneha123-zudo** [comment]
Please assign me this issue under JWOC '24

**Comment by Spandan-Bhattacharya** [comment]
@Sneha123-zudo Go for it!

**Comment by Spandan-Bhattacharya** [comment]
@Sneha123-zudo any updates?

**Comment by Sneha123-zudo** [comment]
Working on it....
