### ISSUE TITLE
Feature Request: Add 6x6 Sudoku Solver

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Spandan-Bhattacharya/Solve_it#2]
This feature request is to implement a 6x6 Sudoku solver, allowing users to input a partially filled 6x6 Sudoku puzzle and obtain the solved solution. 
Assign me this under JWOC'24

**Comment by rahat2134** [comment]
*you cant raise issue before 15 jan

**Comment by Spandan-Bhattacharya** [comment]
I request everyone to read the FAQs section in the discord channel, I will be closing this issue now as mentees are not allowed to create issues before the coding phase begins. Keep the issue noted with you, and raise once the coding phase begins.

**Comment by Spandan-Bhattacharya** [comment]
Closed for now, again raise it after the coding phase begins.

**Comment by Spandan-Bhattacharya** [comment]
I request everyone to read the FAQs section in the discord channel, I will be closing this issue now as mentees are not allowed to create issues before the coding phase begins. Keep the issue noted with you, and raise once the coding phase begins.
