### ISSUE TITLE
Want to style solve it!

### ISSUE THREAD

**Issue by KumariAnkita04** [Spandan-Bhattacharya/Solve_it#21]
The background of page and the name solve it looks dull. I want to style it please assign me this under JWoC'24.

**Comment by Spandan-Bhattacharya** [comment]
Thank You for the interest, but these issues are already mentioned in issues #8 and #19

**Comment by Spandan-Bhattacharya** [comment]
I am closing this issue, if you want to work on this issue, please comment on the issue #8.
