### ISSUE TITLE
Improve Search Bar

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#211]
Currently, when something is searched in the search bar, the drop down is inaccurate. The results are shown in the card form.
Implement:

- Make it so that the drop down shows correct results.
- When the items in the drop down are clicked, the user is redirected to that solver
- When the exit(x) sign is pressed in the search bar, all the solvers should be shown below. Currently, whatever was searched last is shown.

**Comment by Surajit0573** [comment]
Assign this to me under JWOC 2024.

**Comment by Spandan-Bhattacharya** [comment]
@Surajit0573 Go for it!
