### ISSUE TITLE
Change the navbar and footer and style of the FAQ page to that of the contributor page.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#213]
Make it so that the FAQ page stays responsive.
The FAQ UI is like that of the other pages except Homepage.

**Comment by Sneha123-zudo** [comment]
Please assign me this issue under JWOC '24

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @Sneha123-zudo
