### ISSUE TITLE
Improve the 6x6 solver.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#216]
Implement:

1. Make the solver responsive.
2. The input data is shown as Black digits in the solution.
3. The answer data(solved by the solver) is shown as blue coloured digits in the solution.
4. Currently the reset function is not working correctly in terms of resetting the colours(it makes everything black). Fix it such that points 2 and 3 are maintained.
5. Add the solve animation of 9x9 solver.

**Comment by bera474** [comment]
assign me under JWOC 2024

**Comment by Spandan-Bhattacharya** [comment]
@bera474 Go for it!
