### ISSUE TITLE
Improve the 8x8 solver.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#217]
Implement:

1. Make the solver responsive.
2. The input data is shown as Black digits in the solution.
3. The answer data(solved by the solver) is shown as blue coloured digits in the solution.
4. Currently the reset function is not working correctly in terms of resetting the colours(it makes everything black). Fix it such that points 2 and 3 are maintained.
5. Change the font to match the 4x4 solver.
6. Make the grid style match the 4x4 solver style.
7. Add the solve animation of 9x9 solver.

**Comment by Surajit0573** [comment]
Assign this to me under JWOC 2024.

**Comment by Spandan-Bhattacharya** [comment]
@Surajit0573 Go for it!
