### ISSUE TITLE
Add back to home button in the word unjumbler.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#220]

**Comment by sukriti-kuila** [comment]
I would like to work on this

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @sukriti-kuila

**Comment by sukriti-kuila** [comment]
does this work?

https://github.com/Spandan-Bhattacharya/Solve_it/assets/87015685/fe553e3c-0973-49f9-a72c-d892f9165154

**Comment by Spandan-Bhattacharya** [comment]
Yes it does!
