### ISSUE TITLE
Improve input system for the 8 puzzle solver.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#222]
- Add a GUI to enter the numbers for the grid( like the sudoku solvers)
- Add a reset button.
- Make the solver responsive

**Comment by HARSH00M** [comment]
Assign this issue to me.

**Comment by Sneha123-zudo** [comment]
Please assign me this issue under JWOC

**Comment by Spandan-Bhattacharya** [comment]
@Sneha123-zudo Go for it!

**Comment by Spandan-Bhattacharya** [comment]
@Sneha123-zudo any updates?

**Comment by Spandan-Bhattacharya** [comment]
@Sneha123-zudo Any updates?

**Comment by Surajit0573** [comment]
Please assign me to this issue, if it's not completed yet

**Comment by Spandan-Bhattacharya** [comment]
Issue is open for assignment

**Comment by Surajit0573** [comment]
assign me under JWOC 2024

**Comment by Spandan-Bhattacharya** [comment]
@Surajit0573 Go for it!
