### ISSUE TITLE
Improve N queen solver

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#224]
1. Add the feature to generate solutions for all n values from 1 to 10.
2. Make the chess board have a checker board pattern.(alternate dark and light squares)
3. Add a reset button
4. Add a back to home button.

**Comment by HARSH00M** [comment]
Maintainer can you describe problem 1 of this issue

**Comment by Spandan-Bhattacharya** [comment]
@HARSH00M Currently the N queen solver solves for only n=8.
I want it to give the user to choose between values from n=1 to n=10.
then the solver will give the output for the required n value.
Eg: user gives n=4.
So a 4x4 grid with 4 queens correctly placed is the solved answer.

**Comment by Surajit0573** [comment]
Please Assign me this Under JWOC 2024.

**Comment by Spandan-Bhattacharya** [comment]
@Surajit0573 Go for it!
