### ISSUE TITLE
Add Search Bar 

### ISSUE THREAD

**Issue by shrutisk0405** [Spandan-Bhattacharya/Solve_it#23]
Request to add search bar and self-assign under JWOC

Hi @Spandan-Bhattacharya,

I'm interested in adding a search bar to the repository to allow users to easily find specific games or solvers.

I believe this feature would significantly improve the user experience and would like to volunteer to take this on myself under the JWOC label.

Thanks

**Comment by Spandan-Bhattacharya** [comment]
@shrutisk0405 go for it!

**Comment by shrutisk0405** [comment]
Thank you

**Comment by Spandan-Bhattacharya** [comment]
@shrutisk0405 any updates?

**Comment by shrutisk0405** [comment]
Yes i am currently working on it.Actually i have completed the designing part.Its a auto complete search box which will show user the solver he is searching, is available or not ,by comparing the input with tha available list of solvers.
I will complete it by today.

**Comment by Spandan-Bhattacharya** [comment]
Okay good!
