### ISSUE TITLE
Add Navigation and Footer Bar to All Game Pages

### ISSUE THREAD

**Issue by HARSH00M** [Spandan-Bhattacharya/Solve_it#234]
##Description:
We need to add a navigation bar and footer bar to all game pages on SOLVE_IT website to enhance user navigation and provide consistent branding and functionality across the site. Currently, the game pages lack these essential elements, which makes it challenging for users to navigate back to other sections of the website or access additional information easily.

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @HARSH00M

**Comment by HARSH00M** [comment]
Yes, working on it, i will be completed by tonight.

**Comment by Spandan-Bhattacharya** [comment]
Okay!

**Comment by HARSH00M** [comment]
I just opened a pull request can you check is there any conflict.

**Comment by Spandan-Bhattacharya** [comment]
Have you opened the pull request?

**Comment by HARSH00M** [comment]
Yes

**Comment by Spandan-Bhattacharya** [comment]
This issue is available for assignment

**Comment by Sneha123-zudo** [comment]
Please assign me this issue under JWOC'24

**Comment by Spandan-Bhattacharya** [comment]
@Sneha123-zudo Go for it!
