### ISSUE TITLE
Add Light mode and btn to switch to dark mode 

### ISSUE THREAD

**Issue by AaadityaG** [Spandan-Bhattacharya/Solve_it#24]
Please allow me to work on it!

**Comment by Spandan-Bhattacharya** [comment]
@AaadityaG go for it!

**Comment by surendar-05** [comment]
Assigned issues to me  @Spandan-Bhattacharya

**Comment by Spandan-Bhattacharya** [comment]
@AaadityaG any updates?

**Comment by AaadityaG** [comment]
> @AaadityaG any updates?

working on it

**Comment by surendar-05** [comment]
can i go @Spandan-Bhattacharya

**Comment by AaadityaG** [comment]
> can i go @Spandan-Bhattacharya

Bro can you please give me time, why I raised an issue?
There are are several primary tasks..

**Comment by Spandan-Bhattacharya** [comment]
Yes @AaadityaG it is assigned to you. But as its a medium task, give the PR by tomorrow.

**Comment by AaadityaG** [comment]
> Yes @AaadityaG it is assigned to you. But as its a medium task, give the PR by tomorrow.

Sorry I will be unable to deliever till today EOD you can assign someone!

**Comment by Spandan-Bhattacharya** [comment]
Okay

**Comment by Spandan-Bhattacharya** [comment]
@surendar-05 I am assigning you the issue now.

**Comment by AnamNaaz-7** [comment]
Please assign this to me under JWOC

**Comment by Spandan-Bhattacharya** [comment]
any updates @surendar-05

**Comment by Spandan-Bhattacharya** [comment]
I am unassigning the issue @surendar-05

**Comment by Ananyamishra08** [comment]
hello @Spandan-Bhattacharya  i would love to work under JWOC

**Comment by Spandan-Bhattacharya** [comment]
@Ananyamishra08 Go for it!

**Comment by diyabhandari** [comment]
hi, i would like to work on this issue

**Comment by Spandan-Bhattacharya** [comment]
@diyabhandari go for it!

**Comment by vishapraj** [comment]
pls , assign me this issue under 'JWOC'

**Comment by Spandan-Bhattacharya** [comment]
@diyabhandari any updates?

**Comment by AnamNaaz-7** [comment]
Please assign this issue to me under JWOC.

**Comment by diyabhandari** [comment]
> @diyabhandari any updates?

i will start working on it in an hour or two

**Comment by Spandan-Bhattacharya** [comment]
Okay

**Comment by Spandan-Bhattacharya** [comment]
@diyabhandari any updates?

**Comment by Spandan-Bhattacharya** [comment]
@diyabhandari I would be re assigning the issue in the evening if no updates are recieved

**Comment by vishapraj** [comment]
@Spandan-Bhattacharya pls assign me this issue under "JWOC"

**Comment by swetasingh8844** [comment]
@Spandan-Bhattacharya please assign this issue to me

**Comment by Spandan-Bhattacharya** [comment]
@vishapraj you are assigned the issue.

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me @Spandan-Bhattacharya

**Comment by Spandan-Bhattacharya** [comment]
@vishapraj  any updates?

**Comment by Spandan-Bhattacharya** [comment]
@vishapraj any updates?
Otherwise i will assign this issue to someone else.

**Comment by Abhigyan103** [comment]
Assign this issue to me under `JWOC`
