### ISSUE TITLE
User Input in N Queen Solver

### ISSUE THREAD

**Issue by Surajit0573** [Spandan-Bhattacharya/Solve_it#243]
Currently, the N-Queen solver has a feature that allows users to select a queen position by clicking on any square. However, this feature is currently useless as the solver only provides a single solution and does not consider the user's input. 

There may be multiple solutions that include the user's desired position, and the solver should be able to find them. If it is unable to find a solution that includes the user's desired position, it should notify the user and provide one correct solution in case of blank input.

Example : 
- User Input : 

![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/0839aec8-2b0a-4637-80dd-73cfca12d610)

- Current Solution :

![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/0f7456f7-48db-40f6-9a1c-d42c5dd19c88)

- Expected Solution :

![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/af915a2f-d3ec-43b6-93ec-639ab0a041f1)

**Comment by Surajit0573** [comment]
Assign me under JWOC 2024, if approved.

**Comment by Spandan-Bhattacharya** [comment]
@Surajit0573 Go for it!
In case the user provided input has no solution, inform the user and give a random solution.
