### ISSUE TITLE
IMPORTANT: Change in home page.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#244]
We will be adding games to the website( not just solvers anymore).
So for that:
- In home page, in place of the 9 cards for each solver, we will have only 2 cards: 1) PLAY, 2) SOLVE

- once solve is clicked, then the 9 solvers are shown in the same page like right now.

- once play is clicked, then the games(yet to be added) cards will be shown.

- Add 2 dummy cards for 4x4 sudoku and 6x6 sudoku.

**Comment by SohanRC** [comment]
@Spandan-Bhattacharya Assign me

**Comment by Sneha123-zudo** [comment]
Please assign me this issue under JWOC '24 , I am interested in solving this issue

**Comment by Spandan-Bhattacharya** [comment]
As both of you have pending issues from before, the one who gets it resolved faster, will get this issue.

**Comment by Anushkabh** [comment]
kindly assign me this issue under JWOC @Spandan-Bhattacharya

**Comment by Spandan-Bhattacharya** [comment]
@SohanRC Go for it!
