### ISSUE TITLE
Add user itinerary description in travel planner

### ISSUE THREAD

**Issue by shrutisk0405** [Spandan-Bhattacharya/Solve_it#25]
Adding Itinerary Description and Itinerary Builder under JWOC Request

Hi @Spandan-Bhattacharya,

I'm interested in working on expanding our travel planner functionality by adding the mentioned key feature:

Itinerary Description: This feature would allow users to write and save detailed descriptions of their planned trip schedules and activities for each day. Think of it as a personal narrative alongside the calendar view.
![travel plannar](https://github.com/Spandan-Bhattacharya/Solve_it/assets/121231756/9a47b875-cac8-40f0-9376-41db444b15f4)
please assign this task to me.
Thanks
Shruti

**Comment by Spandan-Bhattacharya** [comment]
I think this feature does not relate to our project.

**Comment by Spandan-Bhattacharya** [comment]
I think this feature does not relate to our project.

**Comment by shrutisk0405** [comment]
Okay
