### ISSUE TITLE
Add Connect 4 Game

### ISSUE THREAD

**Issue by Surajit0573** [Spandan-Bhattacharya/Solve_it#264]
I want to add Connect 4 Game.

![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/4d6c8408-cad3-4437-a898-c9bb8cfa53df)

Please Assign me under JWOC 2024, if approved.

**Comment by Spandan-Bhattacharya** [comment]
@Surajit0573 Go for it!
