### ISSUE TITLE
Add 2048 Game

### ISSUE THREAD

**Issue by Surajit0573** [Spandan-Bhattacharya/Solve_it#278]
I want to add 2048 Game. In this game user  use arrow keys to move the tiles. Tiles with the same number merge into one when they touch. Add them up to reach 2048!

![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/383911d4-55d9-458d-8aa6-90dab34a1b59)

Assign me under JWOC 2024.

**Comment by Spandan-Bhattacharya** [comment]
@Surajit0573 Go for it!
