### ISSUE TITLE
Improve 8 puzzle solver.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#279]
All given inputs are not solvable for a 8 puzzle problem.
They follow this rule:
https://www.google.com/amp/s/www.geeksforgeeks.org/check-instance-8-puzzle-solvable/amp/
Currently, the solver does not check for this condition before trying to solve.

Implement:
- This checker
- In case of no solution, inform the user that no solution exists.

**Comment by SohanRC** [comment]
Assign me this issue under JWOC 2024.
