### ISSUE TITLE
Add a Memory Card game

### ISSUE THREAD

**Issue by bera474** [Spandan-Bhattacharya/Solve_it#289]
Add a memory card game !
I am attaching the screenshot here !
![Screenshot 2024-02-19 001547](https://github.com/Spandan-Bhattacharya/Solve_it/assets/118124036/0556a35f-c2a5-47b0-8266-3ab5de1f9cfd)

**Comment by SohanRC** [comment]
Assign me this issue under JWOC 2024 .
