### ISSUE TITLE
Improved Sudoku Games

### ISSUE THREAD

**Issue by Surajit0573** [Spandan-Bhattacharya/Solve_it#291]
I would like to suggest some improvements for all the Sudoku games (4x4, 6x6, 8x8, 9x9)

- Make it Responsive to all devices.
- Improve UI (ex: Add Heart emojis instead of just number at Lives)
- Add a Timer to make the game more interesting.

Assign me under JWOC 2024. if approved.

**Comment by Spandan-Bhattacharya** [comment]
@Surajit0573 Go for it!
