### ISSUE TITLE
Add new game ping pong game

### ISSUE THREAD

**Issue by AftabMankapure** [Spandan-Bhattacharya/Solve_it#296]
Add new game ping pong game

**Comment by AftabMankapure** [comment]
@Spandan-Bhattacharya  pls Assign me under SWOC

**Comment by Spandan-Bhattacharya** [comment]
How will this game be?

**Comment by AftabMankapure** [comment]
User vs Computer 

![Ping pong](https://github.com/Spandan-Bhattacharya/Solve_it/assets/125949765/0091deff-1c27-48a0-b8c5-89bc2bfad2d7)

**Comment by AftabMankapure** [comment]
it is clear then assign me

**Comment by AftabMankapure** [comment]
@Spandan-Bhattacharya  check this
