### ISSUE TITLE
Nav bar links fixing

### ISSUE THREAD

**Issue by thesri** [Spandan-Bhattacharya/Solve_it#3]
The links for contact and about from the nav bar arnt working. we can add the related information there , please kindly assign this issue to me under JWOC 2024

**Comment by Spandan-Bhattacharya** [comment]
Please reopen this issue once the coding phase begins. Mentees cannot raise issues before the coding phase begins.
Keep the issues you find noted with you, then raise them one by one when the coding phase begins.
