### ISSUE TITLE
Feature: Add Favicon to Website (Enhancement)

### ISSUE THREAD

**Issue by rahat2134** [Spandan-Bhattacharya/Solve_it#30]
The current version of the website is missing a favicon, which is a small but essential visual element that appears in the browser tab. This enhancement aims to improve user experience and brand recognition by adding a distinctive favicon to the website.

Steps to Reproduce
Open the website in a browser.
Observe the absence of a favicon in the browser tab.

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya assign this issue to me under JWOC.

**Comment by Spandan-Bhattacharya** [comment]
This is a valid issue, but not big enough to warrant an assignment, can you design a logo for the website? then use that as the Flavicon.

**Comment by Spandan-Bhattacharya** [comment]
Okay I am giving it the Medium tag, but then you need to add the logo, along with the name "Solve it!", to the navigation bar as well.

**Comment by Spandan-Bhattacharya** [comment]
Yes I will be Happy to help

**Comment by DarshSohaliya** [comment]
I would like to work on that issue under JWOC 2024
