### ISSUE TITLE
add new puzzle untangle

### ISSUE THREAD

**Issue by AftabMankapure** [Spandan-Bhattacharya/Solve_it#307]
Add new puzzle untangle

![rectangle](https://github.com/Spandan-Bhattacharya/Solve_it/assets/125949765/5344e7db-f18b-417d-a00a-614a3450e361)

**Comment by AftabMankapure** [comment]
@Spandan-Bhattacharya  pls assign me under JWOC

**Comment by Spandan-Bhattacharya** [comment]
This won't fit the theme of the website.

**Comment by AftabMankapure** [comment]
@Spandan-Bhattacharya  pls check this  once 

![NewUn](https://github.com/Spandan-Bhattacharya/Solve_it/assets/125949765/199cf348-5d01-4316-9cec-f983d0643213)

**Comment by Spandan-Bhattacharya** [comment]
It's good but it won't fit with the other games in the website.

**Comment by AftabMankapure** [comment]
it is not game it is puzzle
