### ISSUE TITLE
Add customised scroll bar to all the pages

### ISSUE THREAD

**Issue by Sneha123-zudo** [Spandan-Bhattacharya/Solve_it#316]
I want to add customised scroll bar to all the games pages , it will make that section looks beautiful. PLease assign me this issue under JWOC'24

**Comment by Spandan-Bhattacharya** [comment]
@Sneha123-zudo Go for it!

**Comment by Spandan-Bhattacharya** [comment]
@Sneha123-zudo Submit the PR before 12, then I can merge it!
