### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by Shubhra-Narang** [Spandan-Bhattacharya/Solve_it#319]
The Text in the Search Bar that says "Search Solver" should be aligned in the centre for better readability and improve the appearance of the search bar overall.

The image of the issue: how the search bar looks currently

<img width="527" alt="Screenshot 2024-02-24 at 3 32 54 PM" src="https://github.com/Spandan-Bhattacharya/Solve_it/assets/143348689/4940cbfa-e20b-4f4e-9c66-cb2b9a856273">

**Comment by Shubhra-Narang** [comment]
I can solve this issue, please assign it to me!

**Comment by Spandan-Bhattacharya** [comment]
It seems like you are working on much older fork of the page.
