### ISSUE TITLE
Enhancement of some game pages

### ISSUE THREAD

**Issue by Sneha123-zudo** [Spandan-Bhattacharya/Solve_it#320]
I want to add navbar and footer to some games pages , where the navbar and footer is added as it is not looking good as the other pages of games contains that and i will also enhance that pages and customised scroll bar that other pages contains. As new addition of some games that pages doesn't contains . Please assign me this  issue under JWOC'24

**Comment by Spandan-Bhattacharya** [comment]
Which pages are you mentioning?

**Comment by Sneha123-zudo** [comment]
There are some games pages like block buster , ping pong

**Comment by Spandan-Bhattacharya** [comment]
Okay.
