### ISSUE TITLE
[enhancement]: add back to home page button

### ISSUE THREAD

**Issue by Anushkabh** [Spandan-Bhattacharya/Solve_it#321]
back to home page button in all the games, that would facilitate the users

**Comment by Anushkabh** [comment]
@Spandan-Bhattacharya kindly assign this issue under jwoc'24

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @Anushkabh

**Comment by Anushkabh** [comment]
kindly merge my pr #328  @Spandan-Bhattacharya
