### ISSUE TITLE
Develop Responsive and Interactive Contact Us Form

### ISSUE THREAD

**Issue by Wadgaonkarprathameshdeepak** [Spandan-Bhattacharya/Solve_it#331]
I will create the contact us form by creating a responsive design that seamlessly adjusts to different screen sizes and interactive user interfaces.

**Comment by Wadgaonkarprathameshdeepak** [comment]
![Screenshot 2024-02-20 113941](https://github.com/Spandan-Bhattacharya/Solve_it/assets/95523666/6dfef509-8acd-40b7-b9ee-e53f91084c23)

**Comment by Spandan-Bhattacharya** [comment]
The form page currently is responsive I think

**Comment by Wadgaonkarprathameshdeepak** [comment]
YES , I can develop interactive contacts  form for your project

Thanks and Regards ,

Prathamesh Wadgaonkar
Computer Science and Engineering Department
Deogiri Institute of Engineering and Management Studies
M.No 8177965141
