### ISSUE TITLE
Adding Hamburger menu for mobile view

### ISSUE THREAD

**Issue by nandita27iitp** [Spandan-Bhattacharya/Solve_it#35]
@Spandan-Bhattacharya Assign this issue to me under jwoc

**Comment by Spandan-Bhattacharya** [comment]
@nandita27iitp go for it!

**Comment by Spandan-Bhattacharya** [comment]
any updates? @nandita27iitp

**Comment by Spandan-Bhattacharya** [comment]
any updates? @nandita27iitp

**Comment by Spandan-Bhattacharya** [comment]
I will be assigning this issue to someone else.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya would like to work on it.

**Comment by Zenitssuu** [comment]
@Spandan-Bhattacharya ,i would like to work on it under JWOC'24

**Comment by Spandan-Bhattacharya** [comment]
@Zenitssuu go for it!

**Comment by Spandan-Bhattacharya** [comment]
@Zenitssuu any updates?

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya i would like to work on it under jwoc'24. :)

**Comment by Zenitssuu** [comment]
> @Zenitssuu any updates?

layout is done for home page, adding it in contact and about us section

**Comment by Spandan-Bhattacharya** [comment]
Okay

**Comment by Spandan-Bhattacharya** [comment]
@Zenitssuu how it it going?

**Comment by Spandan-Bhattacharya** [comment]
@Zenitssuu updates?

**Comment by Zenitssuu** [comment]
adding it in other than home page is getting difficult,

**Comment by Spandan-Bhattacharya** [comment]
Okay then do it for the home page only.
