### ISSUE TITLE
Replacing "Solve it!" with proper image logo.

### ISSUE THREAD

**Issue by rahat2134** [Spandan-Bhattacharya/Solve_it#37]
Currently in main body of website we have Solve it! written which isn't looking good so i think to add a proper image similiar to fav-icon and nav logo .
<img width="751" alt="Screenshot 2024-01-16 at 11 43 24 PM" src="https://github.com/Spandan-Bhattacharya/Solve_it/assets/136263179/218b40a7-203c-48e7-bff6-e498517277f0">
<img width="166" alt="Screenshot 2024-01-16 at 11 44 12 PM" src="https://github.com/Spandan-Bhattacharya/Solve_it/assets/136263179/50aca46d-6d0f-423d-aa03-16454a5d1895">

**Comment by rahat2134** [comment]
@Spandan-Bhattacharya assign me this under jwoc

**Comment by Spandan-Bhattacharya** [comment]
Assigned!

**Comment by surendar-05** [comment]
Assigned this issue to me I have another interesting favicon
