### ISSUE TITLE
`Button Clickability` Issue

### ISSUE THREAD

**Issue by this-is-yaash** [Spandan-Bhattacharya/Solve_it#38]
The buttons contain a button-shaped area, clicking on the entire button doesn't trigger the intended action. Instead, the "try now" text needs to be clicked explicitly for the button to work as expected
This behavior may cause confusion.

So I'd like to work on this issue under **JWoC**

**Comment by Spandan-Bhattacharya** [comment]
@this-is-yaash go for it!
