### ISSUE TITLE
Feature: Color of the heading "Solve it!" isn't clearly visible

### ISSUE THREAD

**Issue by Divyanshgarg-04** [Spandan-Bhattacharya/Solve_it#4]
In the White background the main heading is not clearly visible

<img width="232" alt="Screenshot 2024-01-13 221302" src="https://github.com/Spandan-Bhattacharya/Solve_it/assets/120127517/c29b0cc4-e5f3-4986-b4f2-0b11493733bf">

**Comment by Divyanshgarg-04** [comment]
@Spandan-Bhattacharya please assign this task to me.

**Comment by rahat2134** [comment]
you cant raise the issue before 15

**Comment by Spandan-Bhattacharya** [comment]
Please reopen the issue once the coding phase begins.
