### ISSUE TITLE
Simplify it

### ISSUE THREAD

**Issue by Lakshya0018UP** [Spandan-Bhattacharya/Solve_it#47]
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/122142987/4e416a4c-ee41-4334-9221-12b8712a207d)

**Comment by Lakshya0018UP** [comment]
Simplify this

**Comment by Spandan-Bhattacharya** [comment]
How to recreate this issue? For it looks fine in my computer.

**Comment by Spandan-Bhattacharya** [comment]
As per the rules of the competition, I first have to assign you the issue, after which you can make a PR. Otherwise it won't count towards the points,

**Comment by Lakshya0018UP** [comment]
Try to open in some other device

**Comment by Lakshya0018UP** [comment]
OK 

> As per the rules of the competition, I first have to assign you the issue, after which you can make a PR. Otherwise it won't count towards the points,

OK
