### ISSUE TITLE
fix invisible text 

### ISSUE THREAD

**Issue by GhoshAditi** [Spandan-Bhattacharya/Solve_it#49]
@Spandan-Bhattacharya the text is not visible. i would like to make it visible . please assign it to me under jwoc'24.
![Untitled13](https://github.com/Spandan-Bhattacharya/Solve_it/assets/144611267/706517d0-b1e5-4e2f-a01c-41796e19d718)

**Comment by Spandan-Bhattacharya** [comment]
I am creating another issue to revamp the whole card. So it will be covered in that.

**Comment by Spandan-Bhattacharya** [comment]
I will be opening an issue now. Comment on it to work on it.
