### ISSUE TITLE
Add reset functionality to the 4x4 sudoku solver.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#5]
Implement the gridReset function in sudoku_solver4.js file.

**Comment by Seema-bedara** [comment]
please assign this issue to me , for jwoc 2024.

**Comment by Spandan-Bhattacharya** [comment]
Comment again when the coding phase begins. It will be assigned then as per first cum first serve

**Comment by Seema-bedara** [comment]
Hi,                                                                                                                                                                                                                           I am from JWoC'24 .                                                                                                                                                                                                            I am interested in contributing to this as a part of JWOC.`24 Please assign it to me.

**Comment by Sneha6003** [comment]
I would like to work on that issue under JWOC.

**Comment by thatguywhocode** [comment]
Hello @Spandan-Bhattacharya , I would like to work on this issue under JWOC.

**Comment by Spandan-Bhattacharya** [comment]
@Seema-bedara you are assigned this issue. Good Luck!!

**Comment by Spandan-Bhattacharya** [comment]
Everyone if you have not joined the Discord server yet, please do so, as I will be sharing instructions on the solve-it! channel under projects.
Link to the server:
https://discord.gg/bcgZ9RZZ8r

**Comment by Seema-bedara** [comment]
I have raised the PR please accept it .

**Comment by Spandan-Bhattacharya** [comment]
Merged!
