### ISSUE TITLE
Revamp Home Screen solver cards.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#50]
Change the current card design for the solvers.
Design according to the image.
The final card should look like this:
![Desktop - 2](https://github.com/Spandan-Bhattacharya/Solve_it/assets/95448248/f60cabbe-0d72-437f-8dbf-b381c5206127)

No need to add any animations as of now.

**Comment by GhoshAditi** [comment]
I would like to work on it

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya plz assign it to me

**Comment by Spandan-Bhattacharya** [comment]
@GhoshAditi Go for it!
The details for the fonts:

- font: league spartan
- there is a linear gradient in the card, you can pick the colours using colour picker from the image.
- There is an image of a sudoku grid behind the writjng.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya can you provide me with the link of your latest website? The link i am working with after forking is not working.
![Untitle2d](https://github.com/Spandan-Bhattacharya/Solve_it/assets/144611267/b8855429-01a1-4eb2-b870-1706fffb13ed)
Can you please help me out?

**Comment by Spandan-Bhattacharya** [comment]
Try refreshing the page, the website is hosted at
https://solve-it-self.vercel.app/

**Comment by Spandan-Bhattacharya** [comment]
The live server is not opened at the correct folder.
