### ISSUE TITLE
Fix Background Animation

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#51]
Currently the bubbles of the website animation overflows into the navbar and it comes about the writing and the logo.
You need to:

- Make it so that the animation does not overflow in the navbar and is below the logo and the writing.

**Comment by gitgoap** [comment]
@Spandan-Bhattacharya  ***what do you mean by  "comes about the writing and the logo."*

**Comment by gitgoap** [comment]
Assign it to me under JWOC2024! Thanks @Spandan-Bhattacharya

**Comment by Jenis07** [comment]
Can you assign me this issue under JWOC?

**Comment by gitgoap** [comment]
I am working on this issue, its taking little longer. @Spandan-Bhattacharya

**Comment by Spandan-Bhattacharya** [comment]
Okay

**Comment by gitgoap** [comment]
I am usassigning my self from this issue as I am unable to fix this issue due to the lack of  time. 
**Hope you understand** @Spandan-Bhattacharya

**Comment by AryanPahuja21** [comment]
@Spandan-Bhattacharya please assign this issue to me under JWOC'24

**Comment by Divyanshgarg-04** [comment]
@Spandan-Bhattacharya I would love to work on this issue. Can you please assign it to me under JWOC'24

**Comment by Spandan-Bhattacharya** [comment]
@AryanPahuja21 Go for it!
