### ISSUE TITLE
Improve search bar look.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#52]
The search bar is barely visible in the current look. Make it such that the input field is clearly visible and the text is readable.

Try doing something more than just changing the Input field colour to white.

**Comment by aarshsaxena** [comment]
@Spandan-Bhattacharya  Assign this task to me.

**Comment by Spandan-Bhattacharya** [comment]
@aarshsaxena go for it!
