### ISSUE TITLE
BUG: Fixing the gradient color of Nav Bar, Text not clearly visible

### ISSUE THREAD

**Issue by gitgoap** [Spandan-Bhattacharya/Solve_it#53]
# CSS fix needed
The top navigation bar having dark blue and sky blue blends of gradient colors makes the text '**search solver**" less visible.
Refer Screenshot: 
![Screenshot 2024-01-18 212951](https://github.com/Spandan-Bhattacharya/Solve_it/assets/117789470/d6215bfa-b91f-4cf6-8bc6-da3e9a3be0d3)

**Comment by gitgoap** [comment]
Assign this issue to me! @Spandan-Bhattacharya

**Comment by Spandan-Bhattacharya** [comment]
This has been addressed by the issue #52
