### ISSUE TITLE
UI: Text not aligned in about page

### ISSUE THREAD

**Issue by gitgoap** [Spandan-Bhattacharya/Solve_it#55]
# UI Fix
## #Problem 2: Also the page is half white and half black in the background color.
Refer screenshot: 
![Screenshot 2024-01-18 214917](https://github.com/Spandan-Bhattacharya/Solve_it/assets/117789470/fb63c342-3ed1-44f2-b6ab-51011a0ef064)

**Comment by gitgoap** [comment]
@Spandan-Bhattacharya  Can I work on this issue.

**Comment by Spandan-Bhattacharya** [comment]
@gitgoap go for it!
