### ISSUE TITLE
Stylise the Try Now! link in the home page

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#6]
Make the Try Now! link look like a button.
You can do that by implementing the trynow-button class in styles.css.
Make sure the Button fits the Aesthetic of the page.

**Comment by TejaswaniVelugoti** [comment]
I am interested in contributing to this as a part of JWOC. Please assign it to me.

**Comment by Spandan-Bhattacharya** [comment]
Comment when the coding phase begins. It will be assigned then as per first cum first serve

**Comment by MusharafShaik970** [comment]
I want to contribute here. please , assign me this issue. I will give my best

**Comment by Sruti-sahini** [comment]
Hello @Spandan-Bhattacharya !
I am from JWoC'24
I have a good hold in web development.
Could you please assign me tis issue after the coding period starts?

**Comment by Spandan-Bhattacharya** [comment]
Comment after the coding phase begins, otherwise we are not allowed to assign you the task.

**Comment by Sruti-sahini** [comment]
Hello @Spandan-Bhattacharya 
Please assign me this issue under JWoC'24.

**Comment by thatguywhocode** [comment]
Hello @Spandan-Bhattacharya , I would like to work and contribute on this issue under JWOC.  Kindly assign it to me.

**Comment by Spandan-Bhattacharya** [comment]
@Sruti-sahini you are assigned this issue, best of luck!!

**Comment by ogshashwat17** [comment]
i want too work on this project

**Comment by Spandan-Bhattacharya** [comment]
Everyone if you have not joined the Discord server yet, please do so, as I will be sharing instructions on the solve-it! channel under projects.
Link to the server:
https://discord.gg/bcgZ9RZZ8r

**Comment by gayathrik23** [comment]
@Spandan-Bhattacharya  can you assign me this issue under JWOC.. i would like to contribute
