### ISSUE TITLE
Fix Search Bar `Suggestions Overlay`: Closing Behavior on Click Outside

### ISSUE THREAD

**Issue by this-is-yaash** [Spandan-Bhattacharya/Solve_it#60]
Upon entering a *search keyword*, it displays suggestions according to the input.
For instance, the input "So" shows list of related suggestions.

But when the user click outside the search bar it should close the suggestions bar.

**Expected Behavior:** 
Clicking outside the search bar should close the suggestions, and the suggestions should reappear upon clicking inside the search bar.

**Current Behavior:**
Currently, clicking outside the search bar doesn't close the suggestions. The suggestions only disappear when the entered keywords are deleted. This deviates from the standard behavior observed in most search bars and may lead to user confusion.

If this issue is valid, then assign me to work on this under **JWOC**

**Comment by Spandan-Bhattacharya** [comment]
Yes you can work on it.

**Comment by this-is-yaash** [comment]
Submitted a PR, review it & let me know. 
Thanks!
