### ISSUE TITLE
Setting up the UI of sudoku solver boxes in the front page

### ISSUE THREAD

**Issue by Sruti-sahini** [Spandan-Bhattacharya/Solve_it#63]
I have a good idea to make the sudoku solver boxes look attractive.
Kindly assign me this issue under JWoC'24.
@Spandan-Bhattacharya

**Comment by Spandan-Bhattacharya** [comment]
Which boxes are you mentioning here?

**Comment by vishapraj** [comment]
@Spandan-Bhattacharya  pls assign me this issue under JWOC
