### ISSUE TITLE
make the search bar visible

### ISSUE THREAD

**Issue by GhoshAditi** [Spandan-Bhattacharya/Solve_it#68]
@Spandan-Bhattacharya the search bar is invisible . i would like to change its style and make it visible. plz assign it to me under jwoc'24.
current search bar :
![Untitle423d](https://github.com/Spandan-Bhattacharya/Solve_it/assets/144611267/46804ab1-ab28-4563-81e5-6ca8892f32c5)

**Comment by Spandan-Bhattacharya** [comment]
go for it! @GhoshAditi
