### ISSUE TITLE
Sudoku-solver-4x4: Invalid input alert.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#7]
Currently, if an invalid input is given, an alert box is shown and the user needs to refresh the page to re enter the values.
You need to:

- Change it so that the when an invalid input is given, a message pops up within the website itself, without using the "alert" function.
- The grid gets reset, after the message is shown, thus allowing the user to re-enter the values without refreshing the page.

**Comment by Sneha-Sonkar** [comment]
I would like to work on that issue under JWOC

**Comment by Spandan-Bhattacharya** [comment]
Comment after the coding phase begins. Then I can assign the issue to you based on a first cum first serve basis

**Comment by Prithwi32** [comment]
Hello @Spandan-Bhattacharya I would like to work on that issue under JWOC ...

**Comment by Spandan-Bhattacharya** [comment]
@Prithwi32 you are assigned this issue. Good Luck!!

**Comment by Spandan-Bhattacharya** [comment]
Everyone if you have not joined the Discord server yet, please do so, as I will be sharing instructions on the solve-it! channel under projects.
Link to the server:
https://discord.gg/bcgZ9RZZ8r

**Comment by Prithwi32** [comment]
@Spandan-Bhattacharya I made PR kindly check that once
