### ISSUE TITLE
Redesign About Us Page 

### ISSUE THREAD

**Issue by ramith-kulal** [Spandan-Bhattacharya/Solve_it#70]
### Problem
Our current About Page needs a facelift.

**Proposed Solution**
redesign the page to make it visually attractive.
**Screenshot of current page:**
![Screenshot 2024-01-20 104557](https://github.com/Spandan-Bhattacharya/Solve_it/assets/142984776/25afae46-92a8-45e7-b7fe-a3f7c3fdf3aa)

**Working under JWoC'24**

**Comment by akarshi19** [comment]
I would love to work on this issue. Please assign me this issue under'JWOC'2024'

**Comment by Anshikaa-Saini** [comment]
I would like to work on that issue under JWOC @Spandan-Bhattacharya

**Comment by hittie45** [comment]
I would like to work on this issue under JWOC
@Spandan-Bhattacharya

**Comment by Spandan-Bhattacharya** [comment]
@ramith-kulal Go for it!!

**Comment by Spandan-Bhattacharya** [comment]
Make the about page like this:
