### ISSUE TITLE
i want to work in this project, redesign total navbar and sudoku solver section, please assign it to me under JWOC'24

### ISSUE THREAD

**Issue by Zenitssuu** [Spandan-Bhattacharya/Solve_it#72]
![Screenshot (221)](https://github.com/Spandan-Bhattacharya/Solve_it/assets/154405878/51accf08-da33-41c8-ae15-c27a04ed2553)
i will redesign the navigation bar by styling it (includes home, about, search bar, logo).
and i will design the sudoku section in home page

**Comment by Spandan-Bhattacharya** [comment]
All these are being worked upon by others currently.
