### ISSUE TITLE
Redesigning Contact Us Page

### ISSUE THREAD

**Issue by TanushreeBorase** [Spandan-Bhattacharya/Solve_it#73]
<img width="764" alt="image" src="https://github.com/Spandan-Bhattacharya/Solve_it/assets/130696335/48aed187-71d0-43e1-9f77-72318e8ad1fa">
I would like to give a suggestion to change the colours of titles( Email,Phone,Discord,Github) and other lines in black to white which will go good with blue.I would like to work on this issue under JWOC'24.

**Comment by Anshikaa-Saini** [comment]
I would like to work on that issue under JWOC @Spandan-Bhattacharya

**Comment by hittie45** [comment]
I would like to work on this issue under JWOC @Spandan-Bhattacharya

**Comment by Spandan-Bhattacharya** [comment]
The About Us page will be redesigned as per this:
https://www.figma.com/file/HIY2NL5aXbIEJNjSjx93OT/solve_it?type=design&node-id=0%3A1&mode=design&t=hUlTuybDwlfWsF4X-1
