### ISSUE TITLE
Redesign the Contact Us page and improve the contact form

### ISSUE THREAD

**Issue by Anshikaa-Saini** [Spandan-Bhattacharya/Solve_it#74]
I would like to redesign the contact us form and bring the fields to the center of the page.

Currently the contact form fields are shifted towards the right side of the page which does not look effective. I want to redesign the form.

**Comment by akarshi19** [comment]
I would love to redesign the contact us page form. Please assign me this issue under'JWOC'2024
![desktop2](https://github.com/Spandan-Bhattacharya/Solve_it/assets/93787305/107f572a-a38c-4c45-a30e-3c665298b027)
'

**Comment by Spandan-Bhattacharya** [comment]
@Anshikaa-Saini 
Go for it!
The page needs to be designed as per this:
https://www.figma.com/file/HIY2NL5aXbIEJNjSjx93OT/solve_it?type=design&node-id=0%3A1&mode=design&t=hUlTuybDwlfWsF4X-1

**Comment by prakharsingh-74** [comment]
@Spandan-Bhattacharya i would like to contribute in this issue please assign it to me under JWOC

**Comment by Spandan-Bhattacharya** [comment]
@Anshikaa-Saini Any updates?

**Comment by Anshikaa-Saini** [comment]
yes,
After all the changes I have made till now, it looks like this:
![opensource](https://github.com/Spandan-Bhattacharya/Solve_it/assets/143860130/87ad75b5-f139-4506-be9b-d4ae0da5e3c9)


Still working on it, will let you know further soon.
