### ISSUE TITLE
Bug: Website logo on navbar

### ISSUE THREAD

**Issue by Rishav9911** [Spandan-Bhattacharya/Solve_it#76]
The website logo is present on navigation bar when we are on homepage but it disappears from navbar when we are on about and contact page. I would like to fix that and would add functionality on logo so that if we click on it, it will redirect us to the home page.
Kindly assign this issue to me under JWOC.

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @Rishav9911

**Comment by Rishav9911** [comment]
Thanks alot @Spandan-Bhattacharya , i have made the mentioned changes and sending the pull request for same. 


The contact and about us page now have the below navbar and clicking on logo would take them to the home page.

![Screenshot 2024-01-21 163624](https://github.com/Spandan-Bhattacharya/Solve_it/assets/133174630/c1a4f1f9-b285-4a57-af68-44cd0e6ddc54)

**Comment by Rishav9911** [comment]
Hey @Spandan-Bhattacharya , I have already sent the pull request for above changes, kindy merge it. I can open another issue for the 4x4 sudoku solver for the same and then work on that seperately with another pull request if you don't mind. Thank you.

**Comment by Spandan-Bhattacharya** [comment]
Yeah but the picture is not showing up correctly in my phone( i know the website is not yet responsive, but it showed up previously) Thus i am waiting to try it out on a pc to check for correctness.

**Comment by Rishav9911** [comment]
no issue, I'll open another issue after this is successfully merged.

**Comment by Spandan-Bhattacharya** [comment]
Okay but then reopen the issue after the navbar gets built on the other solver's page.

**Comment by Rishav9911** [comment]
hey, kindly review the pull request @Spandan-Bhattacharya  so i can start working on other issues as well.  Thank you.
