### ISSUE TITLE
Redesign the home page

### ISSUE THREAD

**Issue by Aadhya-Sharma** [Spandan-Bhattacharya/Solve_it#79]
### **Problem : ** 

1) The current home page lacks visual appeal , with an unengaging design. 
2) The color scheme inconsistency hampers the overall cohesiveness of the page.
3) The game cards are also not effective enough.

### **Proposed Solution : **

Redesign the home page by enhancing its visual appeal through cohesive color schemes and also making the game cards effective by using relevant pictures.

### **Screenshots of the current home page**
![Screenshot 2024-01-21 140638](https://github.com/Spandan-Bhattacharya/Solve_it/assets/121510222/0926f394-c986-4f26-9c2e-b85b77a133db)

**Comment by Aadhya-Sharma** [comment]
I would like to work on this issue under JWOC

**Comment by Spandan-Bhattacharya** [comment]
Okay can you give some designs about how you are envisioning the changed look?

**Comment by Aadhya-Sharma** [comment]
Okay I will provide you the same by tomorrow.

**Comment by Aadhya-Sharma** [comment]
The navbar , footer and game cards below, with a comparable colour palette,
are what I'm considering adding.Let me know your opinion.
