### ISSUE TITLE
Provide Background for the homepage

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#8]
Give the homepage a stylized background, with at least one moving element. Eg. some animation, sparkles, etc.
Keep the theme of the webpage among the lighter shades.
Ensure that the entire page has the background.

**Comment by Prithwi32** [comment]
Hello @Spandan-Bhattacharya I would like to work on this issue under JWOC ...
I ensure that to contribute amazing background for the website, Thank You!

**Comment by Spandan-Bhattacharya** [comment]
Comment when the coding phase begins. It will be assigned then as per first cum first serve.

**Comment by Ananyamishra08** [comment]
Hello, @Spandan-Bhattacharya  I would like to work on this , please assign it to me.

**Comment by SGCODEX** [comment]
I would like to work on this issue under JWOC

**Comment by Prithwi32** [comment]
Hello @Spandan-Bhattacharya I would like to work on that issue under JWOC ...
I ensure that to contribute amazing background for the website, Thank You!

**Comment by Spandan-Bhattacharya** [comment]
@Ananyamishra08  you are assigned this issue. Good Luck!!

**Comment by Spandan-Bhattacharya** [comment]
Everyone if you have not joined the Discord server yet, please do so, as I will be sharing instructions on the solve-it! channel under projects.
Link to the server:
https://discord.gg/bcgZ9RZZ8r

**Comment by KumariAnkita04** [comment]
Hey @Spandan-Bhattacharya I want to work on this issue
