### ISSUE TITLE
LinkedIn link and github link is not connected

### ISSUE THREAD

**Issue by prakharsingh-74** [Spandan-Bhattacharya/Solve_it#80]
Please provide a linkedin link and your github link to add in the footer section of the project.
@Spandan-Bhattacharya i would like to work on this issue. Please assign me this issue under JWOC

https://github.com/Spandan-Bhattacharya/Solve_it/assets/148339919/63b98d89-9402-4d67-9719-8452a3fc1db2

**Comment by thatguywhocode** [comment]
Hey @Spandan-Bhattacharya , I want to work on this issue under JWOC

**Comment by Divyanshgarg-04** [comment]
@Spandan-Bhattacharya I would love to work on this issue under JWOC can you please assign this issue to me

**Comment by Spandan-Bhattacharya** [comment]
Go for it! @thatguywhocode 
But ensure that it works for all pages with the footer.
Github: give the link of the repo.
LinkedIn:
https://www.linkedin.com/in/spandan-bhattacharya-02509b227

**Comment by thatguywhocode** [comment]
Okay @Spandan-Bhattacharya

**Comment by prakharsingh-74** [comment]
@Spandan-Bhattacharya I have created the issue first and mention you to resolve it. How can you give this issue to somebody else.
![Screenshot 2024-01-21 201710](https://github.com/Spandan-Bhattacharya/Solve_it/assets/148339919/27ae2c9b-4aa0-49d8-9675-a554e976f25d)


> Okay @Spandan-Bhattacharya

**Comment by Spandan-Bhattacharya** [comment]
Sorry for the mistake.
@prakharsingh-74 made the issue so he will be assigned to the issue.
My apologies @thatguywhocode

**Comment by prakharsingh-74** [comment]
@Spandan-Bhattacharya Thank you for your response

**Comment by prakharsingh-74** [comment]
@Spandan-Bhattacharya Please provide you twitter profile url also to merge in the project.

**Comment by Spandan-Bhattacharya** [comment]
I am not on twitter(X)😅. But the icons looks cool so give the link for the JWoC Twitter.
https://twitter.com/TeamJWOC

**Comment by prakharsingh-74** [comment]
@Spandan-Bhattacharya Sure sir
