### ISSUE TITLE
BUG: Styling of  buttons and heading of 4*4 Sudoku solver page is not implemented(removed)

### ISSUE THREAD

**Issue by Prithwi32** [Spandan-Bhattacharya/Solve_it#84]
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/115262737/d36d4404-d141-4d63-b5d8-25c36ca48f03)
Actually the styling to this page is contributed earlier...but its lost ..so need to fix it

**Comment by Prithwi32** [comment]
@Spandan-Bhattacharya  I would like to work on this issue under JWOC

**Comment by Spandan-Bhattacharya** [comment]
This is my mistake i believe, while merging.

I will be fixing the error shortly.

**Comment by Prithwi32** [comment]
> This is my mistake i believe, while merging.
> 
> I will be fixing the error shortly.

Okay
