### ISSUE TITLE
add a section for user to add their own puzzles

### ISSUE THREAD

**Issue by Komal73** [Spandan-Bhattacharya/Solve_it#85]
to implement 'add puzzles' section in home page for users to add their own puzzles

**Comment by Komal73** [comment]
@Spandan-Bhattacharya kindly assign this under JWOC24

**Comment by Spandan-Bhattacharya** [comment]
Okay you can work on it!
But ask users to send ideas for which puzzle they want a solver.
And as I do not intend to include backend into the project, make it so that the suggestion is mailed to me.
If it means the user will be redirected to gmail to write a mail, then be it.

**Comment by Spandan-Bhattacharya** [comment]
Make sure no backend is required.

**Comment by Komal73** [comment]
@Spandan-Bhattacharya Is it like the users will send their ideas by mail then after approval they can add their games or the maintainers will add the games?

**Comment by Spandan-Bhattacharya** [comment]
Yes

**Comment by Spandan-Bhattacharya** [comment]
@Komal73 any updates? else I have to reassign by tomorrow.

**Comment by Komal73** [comment]
@Spandan-Bhattacharya I'm resolving an issue, I'll update you tomorrow if not able to resolve it.

**Comment by Komal73** [comment]
@Spandan-Bhattacharya please check if this is what you want.

https://github.com/Spandan-Bhattacharya/Solve_it/assets/115211296/40ae389c-22e7-46b6-97f2-6f865a096397

**Comment by Spandan-Bhattacharya** [comment]
Looks good! but can you encase it in a box or something like that.

**Comment by Komal73** [comment]
check now.

https://github.com/Spandan-Bhattacharya/Solve_it/assets/115211296/97772557-931c-43ce-8cfa-9ce0c4809a80

**Comment by Spandan-Bhattacharya** [comment]
Looks good!
