### ISSUE TITLE
Adding Images of 4*4 and 6*6 sudoku

### ISSUE THREAD

**Issue by prakharsingh-74** [Spandan-Bhattacharya/Solve_it#87]
![Screenshot 2024-01-21 214224](https://github.com/Spandan-Bhattacharya/Solve_it/assets/148339919/9246aec0-54e8-402a-a206-6bb643b59b3f)

we can add images on the card of 4*4 sudoku and 6*6 sudoku to make it more interactive for the user.

Kindly please assign me this issue under JWOC

**Comment by Spandan-Bhattacharya** [comment]
The card design implementation is showing some errors.
After I finish fixing it, you can work on it then. We have some designs in mind as per issue #50

**Comment by prakharsingh-74** [comment]
ok

**Comment by Spandan-Bhattacharya** [comment]
@prakharsingh-74 do you see any cohesive way to add pictures of the puzzles in the current card layout?
If yes, you can work on this issue.

**Comment by prakharsingh-74** [comment]
@Spandan-Bhattacharya I have seen the currently updated website. I think now it is no need of image to attach on the card it will decrease the UI of the website now
![Screenshot 2024-01-24 174443](https://github.com/Spandan-Bhattacharya/Solve_it/assets/148339919/5cf96eb1-317d-4f07-94ba-ffd642770c8b)
it is my opinion and now i think this is not any more issue you can close this issue and if you think this is the issue then you can give me your design i will implement that in the website.

**Comment by Spandan-Bhattacharya** [comment]
Okay then i am closing it for now, if I think the UI needs a revamp, I will create issues then. You can work on those.

**Comment by prakharsingh-74** [comment]
sure sir
