### ISSUE TITLE
Sudoku-Solver-4x4: Improve the visual representation.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#9]
Enhance the UI and UX of the solver.
You should(but not limited to):

- Center all the elements
- Stylize the cells of the grid
- Stylize the buttons
- Make so that the boxes(the four 2x2 boxes that make the 4x4 grid) can be distinguished from each other.( Like how in a 9x9 sudoku, we can clearly see 9 individual boxes, 3 in each row)
- Add a background.
- Add a button to go back to the home page.

**Comment by shahil-afroz** [comment]
Can you assign this to me when the coding period of JWOC  24 started ?

**Comment by Spandan-Bhattacharya** [comment]
Comment when the coding phase begins. It will be assigned then as per first cum first serve.

**Comment by shahil-afroz** [comment]
Can you assign this  issue to me under JWOC  24.......

**Comment by Spandan-Bhattacharya** [comment]
Everyone if you have not joined the Discord server yet, please do so, as I will be sharing instructions on the solve-it! channel under projects.
Link to the server:
https://discord.gg/bcgZ9RZZ8r

**Comment by Prithwi32** [comment]
@Spandan-Bhattacharya  I would like to work on that issue under JWOC

**Comment by Spandan-Bhattacharya** [comment]
@Prithwi32 go for it!!

**Comment by Prithwi32** [comment]
> @Prithwi32 go for it!!

Yes! Thank You...
