### ISSUE TITLE
Bug: Bubbles over the text

### ISSUE THREAD

**Issue by gitgoap** [Spandan-Bhattacharya/Solve_it#93]
# Similar to the #51 issue, the bubbles produces in the home page overlay the text.

Screen shot added: 
![Screenshot 2024-01-22 065613](https://github.com/Spandan-Bhattacharya/Solve_it/assets/117789470/f7ef9ead-a794-4f6e-9c9f-fc9691d604e8)

### CSS fix

**Possible Fix: Adding z-index property**

**Comment by Spandan-Bhattacharya** [comment]
Both the bubbles and the text colour are the same, thus it is looking that way, this can be fixed during the uphaul of the homepage UI.
