### ISSUE TITLE
Updating the readme file image with new image

### ISSUE THREAD

**Issue by gitgoap** [Spandan-Bhattacharya/Solve_it#94]
# Description
**Readme File Image is given in this repo is old.**

## Solution

Fixing the old image with new image of the homepage.

# Screenshots
## Old image: 
![Screenshot 2024-01-22 070051](https://github.com/Spandan-Bhattacharya/Solve_it/assets/117789470/e43469b6-1ab3-45a8-add2-e4d6f1b4d9bd)

## New image: 
![Screenshot 2024-01-22 070147](https://github.com/Spandan-Bhattacharya/Solve_it/assets/117789470/15309c1b-b40c-4223-887f-0fd02e1c933a)

**Comment by gitgoap** [comment]
@Spandan-Bhattacharya Can I work under this issue under JWOC? thx!

**Comment by Spandan-Bhattacharya** [comment]
Give updated pictures for all the pages in the site. And update the readme text to help first time contributors setup the repository correctly, by forking, cloning and working on a branch,
