### ISSUE TITLE
Implement the 6x6 sudoku solver.

### ISSUE THREAD

**Issue by Spandan-Bhattacharya** [Spandan-Bhattacharya/Solve_it#95]
Refer to the 4x4 solver code for implementation of the solver functions of the 6x6 sudoku.
The 6x6 solver should have 3 rows, each with 2 columns.
Thus each smaller box will have a height of 2 cells and a width of 3 cells.
Like this:
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/95448248/d4fea953-83eb-4932-9f2f-0a10f3c750d7)
Do not work on the CSS of the page, just implement the bare-bones solver.

**Comment by thatguywhocode** [comment]
Assign me under JWOC

**Comment by Spandan-Bhattacharya** [comment]
@thatguywhocode go for it!!

**Comment by thatguywhocode** [comment]
@Spandan-Bhattacharya , I created pr under JWOC
